version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    # Сети, к которым подключается сервис (по умолчанию создается сеть с именем проекта)
    # networks:
    #  - todo-network # Можно явно задать имя сети

  db:
    image: postgres:16-alpine
    container_name: todo-app-postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
